version: '3.8'

services:
  health-risk-profiler:
    build: .
    ports:
      - "10000:10000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
