"""
Streamlit Frontend for AI-Powered Health Risk Profiler
Connects to FastAPI backend for ML predictions
"""

# ... imports
from datetime import datetime

# ... existing code ...

def analyze_document(file) -> Dict[str, Any]:
    """Call OCR endpoint to extract data from document"""
    try:
        files = {"file": (file.name, file, file.type)}
        response = requests.post(f"{API_URL}/analyze", files=files, timeout=15)
        if response.status_code == 200:
            return response.json()
        return {"error": f"OCR failed: {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}

def generate_report(data: Dict[str, Any], result: Dict[str, Any]) -> str:
    """Generate a text report for download"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"""
    HEALTH RISK ASSESSMENT REPORT
    =============================
    Date: {timestamp}
    ID: {hash(str(timestamp))}
    
    PATIENT PROFILING
    -----------------
    Age: {data['age']} | Sex: N/A | BMI: {data['bmi']}
    BP: {data['systolic_bp']} mmHg | Cholesterol: {data['cholesterol']} mg/dL
    
    LIFESTYLE FACTORS
    -----------------
    Smoker: {data['smoker']}
    Exercise: {data['exercise']}
    Diet: {data['diet']}
    Alcohol: {data['alcohol']}
    Stress Level: {data['stress_level']}/10
    
    RISK ASSESSMENT ANALYSIS
    ------------------------
    Overall Risk Level: {result['risk_level'].upper()}
    Risk Score: {result['risk_score']}/100
    Confidence: {result['confidence']*100:.1f}%
    
    CONTRIBUTING FACTORS
    --------------------
    """
    
    for factor in result.get('top_contributing_factors', []):
        report += f"- {factor['feature'].replace('_', ' ').title()}: {factor['importance']*100:.1f}% contribution\n"
        
    report += f"""
    
    CLINICAL RECOMMENDATIONS
    ------------------------
    """
    
    if result['risk_level'] == 'high':
        report += "- Immediate clinical consultation recommended.\n- Monitor cardiovascular metrics closely."
    elif result['risk_level'] == 'medium':
        report += "- Lifestyle modification recommended (Diet/Exercise).\n- Follow up in 3-6 months."
    else:
        report += "- Maintain current healthy habits.\n- Standard annual check-up."
        
    report += "\n\n=============================\nGenerated by AI Health Risk Profiler v1.0"
    return report

# ... existing main function ...

    # Sidebar additions
    with st.sidebar:
        # ... existing config ...
        
        st.divider()
        st.subheader("📄 OCR Data Import")
        uploaded_file = st.file_uploader("Upload Medical Report / Survey", type=['png', 'jpg', 'jpeg'])
        
        if uploaded_file is not None:
            if st.button("Extract Data", type="primary", use_container_width=True):
                with st.spinner("Scanning document..."):
                    ocr_result = analyze_document(uploaded_file)
                    
                    if "error" in ocr_result:
                        st.error("OCR Failed. Please try a clearer image.")
                    else:
                        st.success("Data Extracted Successfully!")
                        # Auto-fill session state
                        extracted = ocr_result.get("answers", {}) # Adjust based on actual API response structure if needed
                        # Map keys if necessary, strictly updating session_state
                        if 'age' in extracted: st.session_state['age'] = int(extracted['age'])
                        if 'bmi' in extracted: st.session_state['bmi'] = float(extracted['bmi'])
                        if 'smoker' in extracted: st.session_state['smoker'] = bool(extracted['smoker'])
                        # ... mapping other fields ...
                        st.rerun()

    # ... in main content result section ...
                    
                    # Report Download
                    st.markdown("---")
                    col_dl1, col_dl2 = st.columns([3, 1])
                    with col_dl2:
                        report_text = generate_report(input_data, result)
                        st.download_button(
                            label="📥 Download Clinical Report",
                            data=report_text,
                            file_name=f"risk_report_{datetime.now().strftime('%Y%m%d')}.txt",
                            mime="text/plain",
                            use_container_width=True
                        )

    with tab2:
        # ... existing model info ...
        st.markdown("---")
        st.subheader("System Architecture")
        st.markdown("""
        ```mermaid
        graph LR
            A[User / Streamlit UI] -->|JSON/Image| B(FastAPI Gateway)
            B -->|Image| C[OCR Service]
            B -->|Structured Data| D{Model Ensemble}
            D -->|Vote| E[Random Forest]
            D -->|Vote| F[XGBoost]
            D -->|Vote| G[Neural Network]
            E & F & G -->|Weighted Avg| H[Final Risk Score]
            H -->|JSON| A
        ```
        """)
import requests
import json
import plotly.graph_objects as go
import plotly.express as px
from typing import Dict, Any
from datetime import datetime

# Configuration
st.set_page_config(
    page_title="AI Health Risk Profiler",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# API Configuration
API_URL = st.secrets.get("API_URL", "http://127.0.0.1:8000")

# Custom CSS for minimalist professional styling
st.markdown("""
<style>
    .main-header {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 2.5rem;
        font-weight: 700;
        color: #2c3e50;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 1.1rem;
        color: #7f8c8d;
        margin-bottom: 2rem;
    }
    .metric-container {
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 1.5rem;
        background-color: #ffffff;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        text-align: center;
        margin-bottom: 1rem;
    }
    .stButton>button {
        width: 100%;
        border-radius: 4px;
        height: 3rem;
        font-weight: 600;
    }
</style>
""", unsafe_allow_html=True)


def check_api_health() -> bool:
    """Check if API is available"""
    try:
        response = requests.get(f"{API_URL}/health", timeout=5)
        return response.status_code == 200 and response.json().get("ml_available", False)
    except:
        return False


def get_model_info() -> Dict[str, Any]:
    """Get ML model performance metrics"""
    try:
        response = requests.get(f"{API_URL}/model-info", timeout=5)
        if response.status_code == 200:
            return response.json()
        return {}
    except:
        return {}


def predict_health_risk(data: Dict[str, Any]) -> Dict[str, Any]:
    """Call ML prediction endpoint"""
    try:
        response = requests.post(f"{API_URL}/predict", json=data, timeout=10)
        if response.status_code == 200:
            return response.json()
        return {"error": f"API error: {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}


def create_risk_gauge(risk_score: float, risk_level: str) -> go.Figure:
    """Create a professional gauge chart for risk score"""
    colors = {'low': '#2ecc71', 'medium': '#f39c12', 'high': '#e74c3c'}
    
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=risk_score,
        domain={'x': [0, 1], 'y': [0, 1]},
        title={'text': "Risk Score", 'font': {'size': 20, 'color': '#2c3e50'}},
        gauge={
            'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': "#7f8c8d"},
            'bar': {'color': "#2c3e50"},
            'bgcolor': "white",
            'borderwidth': 1,
            'bordercolor': "#e0e0e0",
            'steps': [
                {'range': [0, 30], 'color': '#ebfbf0'},  # Very light green
                {'range': [30, 60], 'color': '#fef7e6'}, # Very light orange
                {'range': [60, 100], 'color': '#fdedec'} # Very light red
            ],
            'threshold': {
                'line': {'color': colors.get(risk_level, '#2c3e50'), 'width': 4},
                'thickness': 0.75,
                'value': risk_score
            }
        }
    ))
    
    fig.update_layout(
        height=300,
        margin=dict(l=20, r=20, t=40, b=20),
        font={'family': "Arial, sans-serif"}
    )
    
    return fig


def create_probability_chart(probabilities: Dict[str, float]) -> go.Figure:
    """Create professional bar chart for probability distribution"""
    categories = [k.capitalize() for k in probabilities.keys()]
    values = [probabilities[k.lower()] * 100 for k in categories]
    colors = ['#2ecc71', '#f39c12', '#e74c3c']
    
    fig = go.Figure(data=[
        go.Bar(
            x=categories,
            y=values,
            marker_color=colors,
            text=[f"{v:.1f}%" for v in values],
            textposition='auto',
            width=0.5
        )
    ])
    
    fig.update_layout(
        title="Prediction Probabilities",
        xaxis_title="Risk Category",
        yaxis_title="Probability (%)",
        height=300,
        margin=dict(l=20, r=20, t=40, b=20),
        yaxis=dict(range=[0, 100]),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )
    
    return fig


def create_feature_importance_chart(factors: list) -> go.Figure:
    """Create horizontal bar chart for feature importance"""
    features = [f['feature'].replace('_', ' ').title() for f in factors]
    importances = [f['importance'] * 100 for f in factors]
    
    fig = go.Figure(go.Bar(
        x=importances,
        y=features,
        orientation='h',
        marker=dict(color='#3498db'),
        text=[f"{imp:.1f}%" for imp in importances],
        textposition='auto',
    ))
    
    fig.update_layout(
        title="Key Contributing Factors",
        xaxis_title="Impact (%)",
        height=300,
        margin=dict(l=20, r=20, t=40, b=20),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )
    
    return fig



def analyze_document(file) -> Dict[str, Any]:
    """Call OCR endpoint to extract data from document"""
    try:
        files = {"file": (file.name, file, file.type)}
        response = requests.post(f"{API_URL}/analyze", files=files, timeout=15)
        if response.status_code == 200:
            return response.json()
        return {"error": f"OCR failed: {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}


def generate_report(data: Dict[str, Any], result: Dict[str, Any]) -> str:
    """Generate a text report for download"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"""
    HEALTH RISK ASSESSMENT REPORT
    =============================
    Date: {timestamp}
    ID: {hash(str(timestamp))}
    
    PATIENT PROFILING
    -----------------
    Age: {data['age']} | Sex: N/A | BMI: {data['bmi']}
    BP: {data['systolic_bp']} mmHg | Cholesterol: {data['cholesterol']} mg/dL
    
    LIFESTYLE FACTORS
    -----------------
    Smoker: {data['smoker']}
    Exercise: {data['exercise']}
    Diet: {data['diet']}
    Alcohol: {data['alcohol']}
    Stress Level: {data['stress_level']}/10
    
    RISK ASSESSMENT ANALYSIS
    ------------------------
    Overall Risk Level: {result['risk_level'].upper()}
    Risk Score: {result['risk_score']}/100
    Confidence: {result['confidence']*100:.1f}%
    
    CONTRIBUTING FACTORS
    --------------------
    """
    
    for factor in result.get('top_contributing_factors', []):
        report += f"- {factor['feature'].replace('_', ' ').title()}: {factor['importance']*100:.1f}% contribution\\n"
        
    report += f"""
    
    CLINICAL RECOMMENDATIONS
    ------------------------
    """
    
    if result['risk_level'] == 'high':
        report += "- Immediate clinical consultation recommended.\\n- Monitor cardiovascular metrics closely."
    elif result['risk_level'] == 'medium':
        report += "- Lifestyle modification recommended (Diet/Exercise).\\n- Follow up in 3-6 months."
    else:
        report += "- Maintain current healthy habits.\\n- Standard annual check-up."
        
    report += "\\n\\n=============================\\nGenerated by AI Health Risk Profiler v1.0"
    return report


# Main App
def main():
    # Header
    st.markdown('<div class="main-header">Health Risk Profiler</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="sub-header">Professional cardiovascular risk assessment system using ensemble machine learning</div>',
        unsafe_allow_html=True
    )
    
    # Check API health
    if not check_api_health():
        st.error("Backend API is unavailable. Please check connection.")
        st.stop()
    
    # Sidebar
    with st.sidebar:
        st.header("Configuration")
        
        # API status
        st.caption("System Status")
        st.success("Connected")
        
        st.divider()
        
        # OCR Upload Section
        st.subheader("📄 OCR Data Import")
        uploaded_file = st.file_uploader("Upload Medical Report / Survey", type=['png', 'jpg', 'jpeg'])
        
        if uploaded_file is not None:
            if st.button("Extract Data from Image", type="primary", use_container_width=True):
                with st.spinner("Scanning document with OCR.space engine..."):
                    ocr_result = analyze_document(uploaded_file)
                    
                    if "error" in ocr_result:
                        st.error("OCR Failed. Please try a clearer image.")
                    else:
                        st.success("Data Extracted Successfully!")
                        # Auto-fill session state from OCR results
                        extracted = ocr_result.get("answers", {})
                        
                        # Map keys to session state
                        if 'age' in extracted: st.session_state['age'] = int(extracted['age'])
                        if 'bmi' in extracted: st.session_state['bmi'] = float(extracted['bmi'])
                        if 'smoker' in extracted: st.session_state['smoker'] = bool(extracted['smoker'])
                        if 'systolic_bp' in extracted: st.session_state['systolic_bp'] = int(extracted.get('systolicbp', extracted.get('systolic_bp', 120)))
                        if 'cholesterol' in extracted: st.session_state['cholesterol'] = int(extracted['cholesterol'])
                        
                        st.rerun()

        st.divider()
        
        # Quick test profiles
        st.subheader("Test Profiles")
        
        if st.button("Load High Risk Profile"):
            st.session_state.update({
                'age': 55, 'bmi': 32.0, 'systolic_bp': 160, 'cholesterol': 260,
                'smoker': True, 'exercise': 'never', 'diet': 'high fat',
                'family_history': True, 'sleep_hours': 5.0, 'alcohol': 'heavy',
                'stress_level': 9
            })
        
        if st.button("Load Low Risk Profile"):
            st.session_state.update({
                'age': 28, 'bmi': 22.0, 'systolic_bp': 110, 'cholesterol': 170,
                'smoker': False, 'exercise': 'daily', 'diet': 'balanced',
                'family_history': False, 'sleep_hours': 8.0, 'alcohol': 'none',
                'stress_level': 2
            })
            
        st.divider()
        
        # Model info in sidebar
        with st.expander("Model Architecture"):
            st.caption("Ensemble Model Performance")
            model_info = get_model_info()
            if model_info:
                for model_name, metrics in model_info.get('performance', {}).items():
                    st.text(f"{model_name.replace('_', ' ').title()}")
                    st.progress(metrics['accuracy'])
                    st.caption(f"Accuracy: {metrics['accuracy']*100:.1f}%")

    
    # Main content tabs
    tab1, tab2, tab3 = st.tabs(["Assessment", "Model Details", "Documentation"])
    
    with tab1:
        st.subheader("Patient Data Entry")
        
        # Create form
        with st.form("risk_assessment_form"):
            col1, col2, col3 = st.columns(3)
            
            with col1:
                st.markdown("**Physical Metrics**")
                age = st.number_input("Age (years)", min_value=18, max_value=100, 
                                     value=st.session_state.get('age', 45))
                bmi = st.number_input("BMI", min_value=15.0, max_value=50.0, 
                                     value=st.session_state.get('bmi', 25.0), step=0.1)
                systolic_bp = st.number_input("Systolic BP (mmHg)", min_value=90, max_value=200,
                                             value=st.session_state.get('systolic_bp', 120))
                cholesterol = st.number_input("Cholesterol (mg/dL)", min_value=100, max_value=400,
                                             value=st.session_state.get('cholesterol', 200))
            
            with col2:
                st.markdown("**Lifestyle Indicators**")
                smoker = st.checkbox("Current Smoker", value=st.session_state.get('smoker', False))
                exercise = st.selectbox("Exercise Frequency", 
                                       ['never', 'rarely', 'occasionally', 'regularly', 'daily'],
                                       index=['never', 'rarely', 'occasionally', 'regularly', 'daily'].index(
                                           st.session_state.get('exercise', 'occasionally')))
                diet = st.selectbox("Diet Quality",
                                   ['poor', 'average', 'good', 'balanced', 'high fat', 'high sugar'],
                                   index=['poor', 'average', 'good', 'balanced', 'high fat', 'high sugar'].index(
                                       st.session_state.get('diet', 'balanced')))
                alcohol = st.selectbox("Alcohol Consumption",
                                      ['none', 'light', 'moderate', 'heavy'],
                                      index=['none', 'light', 'moderate', 'heavy'].index(
                                          st.session_state.get('alcohol', 'light')))
            
            with col3:
                st.markdown("**Medical History**")
                family_history = st.checkbox("Family History of Heart Disease",
                                            value=st.session_state.get('family_history', False))
                sleep_hours = st.slider("Daily Sleep (hours)", 3.0, 12.0,
                                       value=st.session_state.get('sleep_hours', 7.0), step=0.5)
                stress_level = st.slider("Stress Level (Self-reported 1-10)", 1, 10,
                                        value=st.session_state.get('stress_level', 5))
            
            st.markdown("---")
            submit_button = st.form_submit_button("Analyze Risk Profile", type="primary", use_container_width=True)
        
        # Make prediction
        if submit_button:
            with st.spinner("Processing data..."):
                input_data = {
                    "age": age, "bmi": bmi, "systolic_bp": systolic_bp, "cholesterol": cholesterol,
                    "smoker": smoker, "exercise": exercise, "diet": diet,
                    "family_history": family_history, "sleep_hours": sleep_hours,
                    "alcohol": alcohol, "stress_level": stress_level
                }
                
                result = predict_health_risk(input_data)
                
                if "error" in result:
                    st.error(f"Error: {result['error']}")
                else:
                    # Display results in a clean layout
                    st.markdown("### Analysis Results")
                    
                    risk_level = result['risk_level']
                    confidence = result['confidence']
                    risk_score = result['risk_score']
                    
                    # Result Banner
                    color_map = {"low": "#27ae60", "medium": "#f39c12", "high": "#c0392b"}
                    bg_color = color_map.get(risk_level, "#34495e")
                    
                    st.markdown(f"""
                    <div style="background-color: {bg_color}; color: white; padding: 1rem; border-radius: 5px; margin-bottom: 2rem; text-align: center;">
                        <h2 style="margin:0; font-family: sans-serif;">{risk_level.upper()} RISK DETECTED</h2>
                        <p style="margin:0; opacity: 0.9;">Confidence Level: {confidence*100:.1f}%</p>
                    </div>
                    """, unsafe_allow_html=True)
                    
                    # Columns for charts
                    col_metrics, col_chart = st.columns([1, 1])
                    
                    with col_metrics:
                        fig_gauge = create_risk_gauge(risk_score, risk_level)
                        st.plotly_chart(fig_gauge, use_container_width=True)
                        
                        st.markdown("#### Top Risk Contributors")
                        factors = result.get('top_contributing_factors', [])
                        if factors:
                            for factor in factors:
                                name = factor['feature'].replace('_', ' ').title()
                                importance = factor['importance'] * 100
                                st.progress(factor['importance'], text=f"{name} ({importance:.1f}%)")
                    
                    with col_chart:
                        probabilities = result.get('probabilities', {})
                        fig_prob = create_probability_chart(probabilities)
                        st.plotly_chart(fig_prob, use_container_width=True)
                        
                        st.markdown("#### Model Consensus")
                        model_preds = result.get('model_predictions', {})
                        for model, pred in model_preds.items():
                            st.write(f"**{model.replace('_', ' ').title()}**: {pred.upper()}")
                    
                    # Recommendations
                    st.markdown("---")
                    st.subheader("Clinical Recommendations")
                    
                    if risk_level == "high":
                        st.warning("⚠️ Immediate clinical consultation recommended. Monitor cardiovascular metrics.")
                    elif risk_level == "medium":
                        st.info("ℹ️ Lifestyle modification recommended. Follow up in 3-6 months.")
                    else:
                        st.success("✅ Maintain current healthy lifestyle habits. Standard annual check-up.")
                    
                    # Report Download
                    st.markdown("---")
                    col_dl1, col_dl2 = st.columns([3, 1])
                    with col_dl2:
                        report_text = generate_report(input_data, result)
                        st.download_button(
                            label="📥 Download Clinical Report",
                            data=report_text,
                            file_name=f"risk_report_{datetime.now().strftime('%Y%m%d')}.txt",
                            mime="text/plain",
                            use_container_width=True
                        )

    with tab2:
        st.subheader("Model Performance Metrics")
        st.markdown("""
        The system utilizes an ensemble of three distinct machine learning architectures:
        1.  **Random Forest**: For robust feature importance analysis.
        2.  **XGBoost**: Gradient boosting for high predictive accuracy.
        3.  **Neural Network**: Multilayer Perceptron for complex pattern recognition.
        """)
        
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Random Forest Accuracy", "88.2%")
        with col2:
            st.metric("XGBoost Accuracy", "93.3%")
        with col3:
            st.metric("Neural Network Accuracy", "95.9%")
            
    with tab3:
        st.subheader("System Documentation")
        st.markdown("""
        ### Methodology
        This tool aggregates inputs across 3 vectors (Physical, Lifestyle, Medical History) to generate a composite risk score.
        
        **Privacy Note**: Use compliant data handling practices. No PII is stored.
        
        **Version**: 1.0.0-Production
        """)
        
        st.subheader("System Architecture")
        st.markdown("""
        ```mermaid
        graph LR
            A[User / Streamlit UI] -->|JSON/Image| B(FastAPI Gateway)
            B -->|Image| C[OCR Service]
            B -->|Structured Data| D{Model Ensemble}
            D -->|Vote| E[Random Forest]
            D -->|Vote| F[XGBoost]
            D -->|Vote| G[Neural Network]
            E & F & G -->|Weighted Avg| H[Final Risk Score]
            H -->|JSON| A
        ```
        """)

if __name__ == "__main__":
    main()
