from datetime import datetime
from typing import Dict, Any

def generate_report(data: Dict[str, Any], result: Dict[str, Any]) -> str:
    """Generate a formatted text report for download"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"""
    HEALTH RISK ASSESSMENT REPORT
    =============================
    Date: {timestamp}
    ID: {hash(str(timestamp))}
    
    PATIENT PROFILING
    -----------------
    Age: {data['age']} | Sex: N/A | BMI: {data['bmi']}
    BP: {data['systolic_bp']} mmHg | Cholesterol: {data['cholesterol']} mg/dL
    
    LIFESTYLE FACTORS
    -----------------
    Smoker: {data['smoker']}
    Exercise: {data['exercise']}
    Diet: {data['diet']}
    Alcohol: {data['alcohol']}
    Stress Level: {data['stress_level']}/10
    
    RISK ASSESSMENT ANALYSIS
    ------------------------
    Overall Risk Level: {result['risk_level'].upper()}
    Risk Score: {result['risk_score']}/100
    Confidence: {result['confidence']*100:.1f}%
    
    CONTRIBUTING FACTORS
    --------------------
    """
    
    for factor in result.get('top_contributing_factors', []):
        report += f"- {factor['feature'].replace('_', ' ').title()}: {factor['importance']*100:.1f}% contribution\n"
        
    report += f"""
    
    CLINICAL RECOMMENDATIONS
    ------------------------
    """
    
    if result['risk_level'] == 'high':
        report += "- Immediate clinical consultation recommended.\n- Monitor cardiovascular metrics closely."
    elif result['risk_level'] == 'medium':
        report += "- Lifestyle modification recommended (Diet/Exercise).\n- Follow up in 3-6 months."
    else:
        report += "- Maintain current healthy habits.\n- Standard annual check-up."
        
    report += "\n\n=============================\nGenerated by AI Health Risk Profiler v1.0"
    return report
